project:
  type: website
  output-dir: docs

website:
  title: "Coco Zhou - CPLN 5920 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Labs"
        menu:
          - href: labs/lab_0/lab0_template.qmd
            text: "Lab 0"
          - href: labs/lab_1/lab1.qmd
            text: "Lab 1"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
